language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features
  - cargo build --verbose
  - cargo test --verbose
